# ?????? ?? ??
server:
  port: 80


spring:
  # MySQL ?? ??
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/gobook?serverTimezone=Asia/Seoul
    username: gobook
    password: cos1234

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create # ?????? ??? ??
    properties:
      hibernate:
        show_sql: true # ???? ?? ?? ??
        format_sql: true # ???? ???? ??? ???? ?? ???
    database-platform: org.hibernate.dialect.MySQL8Dialect